version: '2.1'

services:
  web:
    build: .
    command: python3 -m rest
    ports:
      - "9001:9001"
    volumes:
      - .:/dev-challenge
    links:
      - db
      - keywords
      - pay_service
    restart: always
    depends_on:
      db:
        condition: service_healthy
  keywords:
    build: .
    command: python3 -u gen_keywords/main.py
    ports:
      - "9002:9002"
    restart: always
  pay_service:
    build: .
    command: python3 -m pay_service
    ports:
      - "9003:9003"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/dev-challenge --quiet
      interval: 5s
      timeout: 5s
      retries: 12
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5